apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: atask1
spec:
  steps:
  - name: emptylogs-step-one
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'for i in {1..10}; do echo GONLOGGIN && sleep 3; done;']
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: emptylogs
spec:
  steps:
  - name: quickandonelinefirst
    image: ubuntu
    command: ['bash']
    args: ['-c', 'echo "Hello World!"'] 
  - name: emptylogs-step-one
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'for i in {1..10}; do echo GONLOGGIN && sleep 3; done;']
  - name: emptylogs-step-two
    image: ubuntu
    command: ['bash']
    args: ['-c', 'for i in {1..2}; do sleep 3; done;'] 
  - name: quickandempty
    image: ubuntu
    command: ['bash']
    args: ['-c', ''] 
  - name: quickandempty2
    image: ubuntu
    command: ['bash']
    args: ['-c', ''] 
  - name: quickandoneline
    image: ubuntu
    command: ['bash']
    args: ['-c', 'echo "Hello World!"'] 
---
#The Output of the first Task (git resource) create-file is given as an `Input`
# to the next `Task` check-stuff-file-exists using`from` clause.

apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: 999-working-logs-long
spec:
  tasks:
  - name: atask1
    taskRef:
      name: atask1
  - name: emptylogs
    taskRef:
      name: emptylogs
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: message
      description: The message to print
      default: This is the default message
  resourcetemplates:
    - apiVersion: tekton.dev.what/v1alpha1
      kind: PipelineResource
      metadata:
        name: git-source-$(uid)
        labels:
          triggertemplated: "true"
          generatedBy: "triggers-example"
      spec:
        type: git
        params:
        - name: revision
          value: $(params.gitrevision)
        - name: url
          value: $(params.gitrepositoryurl)
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: cutting-down-trees-run
        labels:
          triggertemplated: "true"
          generatedBy: "triggers-example"
      spec:
        pipelineRef:
          name: 999-working-logs-long
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-binding
spec:
  params:
    - name: gitrevision
      value: $(event.head_commit.id)
    - name: gitrepositoryurl
      value: $(event.repository.url)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: manual-pipeline-binding
spec:
  params:
    - name: gitrevision
      value: v0.32.0
    - name: gitrepositoryurl
      value: https://github.com/GoogleContainerTools/skaffold
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: pipeline-binding
      template:
        name: pipeline-template
      params:
        - name: message
          value: Hello from the Git Triggers EventListener!
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: manual-listener
spec:
  triggers:
    - binding:
        name: manual-pipeline-binding
      template:
        name: pipeline-template
      params:
        - name: message
          value: Hello from the Manual Triggers EventListener!
